TASK1

In [62]:
import numpy as  np
import time

In [63]:
arr_1d=np.arange(1,11)

In [64]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr_2d=np.arange(1,10).reshape(3,3)

In [66]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr_3d=np.random.rand(3,5,3)
arr_3d

array([[[0.39217296, 0.04115659, 0.92330057],
        [0.40623497, 0.94428218, 0.72272449],
        [0.91831995, 0.82326754, 0.6468967 ],
        [0.06793902, 0.83881577, 0.6928224 ],
        [0.95799151, 0.14222247, 0.08777354]],

       [[0.51887998, 0.35993237, 0.96027368],
        [0.70377222, 0.44599407, 0.19220875],
        [0.44288141, 0.46628642, 0.00914256],
        [0.25721541, 0.2453717 , 0.38102144],
        [0.42403833, 0.26753056, 0.11264625]],

       [[0.13867957, 0.68820216, 0.95588973],
        [0.34485436, 0.14278639, 0.2600578 ],
        [0.15217505, 0.19473966, 0.66216051],
        [0.38492733, 0.25045429, 0.58115791],
        [0.89782395, 0.02442901, 0.59671877]]])

In [68]:
np.shape(arr_1d)


(10,)

In [69]:
np.shape(arr_2d)

(3, 3)

In [70]:
np.shape(arr_3d)

(3, 5, 3)

In [71]:
np.size(arr_1d)

10

In [72]:
np.size(arr_2d)

9

In [73]:
np.size(arr_3d)

45

In [74]:
arr_1d.dtype

dtype('int64')

In [75]:
arr_2d.dtype

dtype('int64')

In [76]:
arr_3d.dtype

dtype('float64')

Task2

In [77]:
array=np.array([10,20,30,40,50,60,70,80,90])

In [78]:
array[0:3]

array([10, 20, 30])

In [79]:
array[0::2]

array([10, 30, 50, 70, 90])

In [80]:
array[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

Task 3

In [81]:
arr1=np.random.randint(1,20,size=5)

In [82]:
arr2=np.random.randint(1,20,size=5)

In [83]:
arr1

array([17,  5,  5, 14,  8], dtype=int32)

In [84]:
arr2

array([ 3, 12,  3,  8, 18], dtype=int32)

In [85]:
add=arr1+arr2

In [86]:
add

array([20, 17,  8, 22, 26], dtype=int32)

In [87]:
sub=arr1-arr2
sub

array([ 14,  -7,   2,   6, -10], dtype=int32)

In [88]:
mul=arr1*arr2

In [89]:
mul

array([ 51,  60,  15, 112, 144], dtype=int32)

In [90]:
div=arr1/arr2
div

array([5.66666667, 0.41666667, 1.66666667, 1.75      , 0.44444444])

In [91]:
arr1.mean()

np.float64(9.8)

In [92]:
arr1.std()

np.float64(4.874423042781577)

In [93]:
arr1.var()

np.float64(23.76)

In [94]:
np.median(arr1)

np.float64(8.0)

In [95]:
arr2.min()

np.int32(3)

In [96]:
arr2.max()

np.int32(18)

Task4

In [97]:
nums1=np.arange(1,13)
nums1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
nums2=nums1.reshape(4,3)
nums2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
nums2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [100]:
nums1.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Task 5

In [101]:
n1=np.random.randint(10,50,size=15)

In [102]:
n1

array([44, 47, 24, 16, 11, 45, 23, 13, 45, 36, 32, 21, 40, 49, 12],
      dtype=int32)

In [103]:
n1[n1>25]

array([44, 47, 45, 45, 36, 32, 40, 49], dtype=int32)

In [104]:
n1[n1<30]=0

In [105]:
v=n1[n1%5==0]

In [106]:
len(v)

10

Task 6

In [107]:
ar=np.linspace(0,1,10)

In [108]:
ar

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [109]:
ar=np.identity(4)
ar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
n1=np.random.randint(1,100,size=20)
n1

array([27, 65, 77,  9, 66, 48, 29, 54, 54, 25,  4, 32, 26, 51, 86, 58, 99,
       79, 88, 54], dtype=int32)

TASK 6

In [111]:
arr=np.linspace(0,1,10)

In [112]:
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [113]:
ar=np.identity(4)
ar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
arr1=np.random.randint(1,100,size=20)
arr1

array([54, 46, 65, 50,  5, 39, 88, 92, 81,  2, 68, 85, 99,  8, 81, 99, 15,
       67, 21, 22], dtype=int32)

In [115]:
arr1.sort()

In [116]:
arr1

array([ 2,  5,  8, 15, 21, 22, 39, 46, 50, 54, 65, 67, 68, 81, 81, 85, 88,
       92, 99, 99], dtype=int32)

In [117]:
arr1[len(arr1)-5:len(arr1)]

array([85, 88, 92, 99, 99], dtype=int32)

TASK 7

In [118]:
np.random.seed(0)
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

In [119]:
start_time = time.time()
C = np.dot(A, B) 

In [120]:
try:
    det_C = np.linalg.det(C)
    print(f"Determinant of the result matrix: {det_C:.4e}")
except np.linalg.LinAlgError:
    print("Determinant could not be calculated.")

Determinant of the result matrix: 6.0159e+50


In [121]:
try:
    inv=np.linalg.inv(C)
    print("calculated")
except np.linalg.LinAlgError:
    print('error')



calculated


In [122]:
end_time = time.time()
time_taken = end_time - start_time
time_taken

0.10149145126342773